# Generated by Django 4.2.1 on 2023-06-05 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='goods_list',
            field=models.ManyToManyField(to='core.goods'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
