# Generated by Django 4.2.1 on 2023-06-05 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_basket_goods_list_alter_goods_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
