# Generated by Django 4.2.1 on 2023-06-06 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_goods_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Goods',
            new_name='Good',
        ),
    ]
