# Generated by Django 4.2.1 on 2023-06-06 10:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_rename_goods_good'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Basket',
            new_name='Cart',
        ),
    ]
