# Generated by Django 4.2.1 on 2023-06-10 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_basket_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
